
version: 2

sources:
  - name: external_source
    meta:
      external_location: "read_csv('../imdb_files/{name}.tsv.gz', delim='\t', quote='', all_varchar=true, header=true, AUTO_DETECT=TRUE)"
    tables:
      - name: name.basics
      - name: title.akas
      - name: title.basics
      - name: title.crew
      - name: title.principals
      - name: title.ratings
      - name: title.episode

models:
  #- name: title_akas_model
  - name: cleansed_title_akas_model
    description: "A regional title alias"
    tests:
      - array_column_has_specific_values:
          id_column : titleId
          array_column: types
          value_list:
            - alternative
            - tv
            - dvd
            - festival
            - video
            - working
            - original
            - imdbDisplay
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - titleId
            - ordering
    columns:
      - name: titleId
        description: "an alphanumeric identifier of the title"
        tests:
          - not_null
      - name: ordering
        description: "a number to uniquely identify rows for a given titleId"
        tests:
          - not_null
      - name: title
        description: "the localized title"
        tests:
          - not_null
      - name: region
        description: "the region for this version of the title"
        tests:
          - relationships:
              to: ref('countries_with_regional_codes')
              field: alpha2
      - name: language
        description: "the language of the title"
        tests:
          - relationships:
              to: ref('language_codes')
              field: alpha2
      - name: types
        description: 'Enumerated set of attributes for this alternative title. New values may be added in the future without warning'
        tests:
          - not_null
      - name: attributes
        tests:
          - not_null
        description: "Additional terms to describe this alternative title, not enumerated"
      - name: isOriginalTitle
        description: "if this title is original, or not or unknown"
  - name: title_basics_model
    description: "The characteristics of the title"
    tests:
      - dbt_utils.expression_is_true:
            expression: "len(genres) < 4"
    columns:
      - name: tconst
        description: "alphanumeric unique identifier of the title"
        tests:
          - unique
          - not_null
      - name: titleType
        description: "the type/format of the title (e.g. movie, short, tvseries, tvepisode, video, etc)"
        tests:
          - not_null
      - name: primaryTitle
        description: "the more popular title / the title used by the filmmakers on promotional materials at the point of release"
        tests:
          - not_null
      - name: originalTitle
        description: "original title, in the original language"
        tests:
          - not_null
      - name: isAdult
        description: "adult film"
        tests:
          - not_null
      - name: startYear
        description: "represents the release year of a title. In the case of TV Series, it is the series start year"
        tests:
          - dbt_utils.expression_is_true:
              expression: ' between 1000 and 9999'
      - name: endYear
        description: "TV Series end year. null for all other title types"
        tests:
          - dbt_utils.expression_is_true:
              expression: ' between 1000 and 9999'
      - name: runtimeMinutes
        description: "primary runtime of the title, in minutes"
      - name: genres
        description: "includes up to three genres associated with the title"
        tests:
          - not_null
  # - name: title_crew_model
  #   description: "The crew working on the production  of the title"
  #   columns:
  #     - name: tconst
  #       description: "alphanumeric unique identifier of the title"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: directors
  #       description: "director(s) of the given title"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: writers
  #       description: "writer(s) of the given title"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  # - name: title_episode_model
  #   description: "The episode data"
  #   columns:
  #     - name: tconst
  #       description: "alphanumeric identifier of episode"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: parentTconst
  #       description: "alphanumeric identifier of the parent TV Series"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: seasonNumber
  #       description: "season number the episode belongs to"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: episodeNumber
  #       description: "episode number of the tconst in the TV series"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  # - name: title_principals_model
  #   description: "The principals of a title"
  #   columns:
  #     - name: tconst
  #       description: "alphanumeric unique identifier of the title"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: ordering
  #       description: "a number to uniquely identify rows for a given titleId"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: nconst
  #       description: "alphanumeric unique identifier of the name/person"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: category
  #       description: "the category of job that person was in"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: job
  #       description: "the specific job title if applicable"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: characters
  #       description: "the name of the character played if applicable,"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  - name: title_ratings_model
    description: "The ratings of a title"
    columns:
      - name: tconst
        description: "alphanumeric unique identifier of the title"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('title_basics_model')
              field: tconst
      - name: averageRating
        description: "weighted average of all the individual user ratings"
        tests:
          - not_null
      - name: numVotes
        description: "number of votes the title has received"
        tests:
          - not_null
  # - name: name_basics_model
  #   description: "The details for contributors"
  #   columns:
  #     - name: nconst
  #       description: "alphanumeric unique identifier of the name/person"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: primaryName
  #       description: "name by which the person is most often credited"
  #       tests:
  #         - is_nconst_array
  #         - not_null
  #     - name: birthYear
  #       description: "in YYYY format"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: deathYear
  #       description: "in YYYY format if applicable"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: primaryProfession
  #       description: "the top-3 professions of the person"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: knownForTitles
  #       description: "titles the person is known for"
  #       tests:
  #         - unique
  #         - not_null